operator = "join"
state = "materialized_view"
port = "50350"

maxWorkers = 4
maxJobQueue = 10000

[[InputSchema]]
table = "stories"
[[InputSchema.Attributes]]
key = "id"
type = "int"
[[InputSchema.Attributes]]
key = "user_id"
type = "int"
[[InputSchema.Attributes]]
key = "title"
type = "string"
[[InputSchema.Attributes]]
key = "description"
type = "string"
[[InputSchema.Attributes]]
key = "short_id"
type = "string"

[[InputSchema]]
table = "votes_sum"
[[InputSchema.Attributes]]
key = "story_id"
type = "int"
[[InputSchema.Attributes]]
key = "vote_sum"
type = "int"


# assumptions
# - the first attribute in 'Projection' is the one to use for the join and is treated as libqpu.INT
#   (better make sure it actually is libqpu.INT)
# - the order of JoinConfig.Source entries match the order of connecions
# - i.e. the 1st entry of source is used to construct queries that are then sent to
#   the 1st connection, etc.
[[JoinConfig.Source]]
table = "stories"
joinAttribute = "id"
[[JoinConfig.Source]]
table = "votes_sum"
joinAttribute = "story_id"

[Evaluation]
tracing = false
logTimestamps = false

[[connections]]
address = "dsdriver:50150"
local = "local"
[[connections]]
address = "sum:50250"
local = "local"

[StateBackend]
endpoint = "127.0.0.1:3306"

[StateBackend.Credentials]
accessKeyID = "root"
secretAccessKey = "verySecrectQPUPwd"
