operator = "aggregation"
state = "materialized_view"
port = "50250"

maxWorkers = 4
maxJobQueue = 10000

[[InputSchema]]
table = "buck"
[InputSchema.DownstreamQuery]
isNull = ["comment_id"]
[[InputSchema.Attributes]]
key = "story_id"
type = "int"
[[InputSchema.Attributes]]
key = "vote"
type = "int"

[AggregationConfig]
AggregationFunc = "sum"
AggregationAttribute = "vote"
GroupBy = "story_id"

[Evaluation]
tracing = false
logTimestamps = false

[[connections]]
address = "127.0.0.1:50150"
local = "local"

[StateBackend]
endpoint = "127.0.0.1:3308"

[StateBackend.Credentials]
accessKeyID = "root"
secretAccessKey = "verySecrectQPUPwd"
